title: RC Racing in America
author: terickso25
email: terickso25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  RC racing is awesome, everyone needs to try it!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
